from pyqtgraph import PlotWidget
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget, QGridLayout, QComboBox, \
    QApplication, QGroupBox, QVBoxLayout, QCheckBox, QLabel, \
    QMainWindow, QPushButton, QAction, QMessageBox, QLCDNumber
import string

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(981, 386)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_1 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_1.setObjectName("verticalLayout_1")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.verticalLayout_1.addLayout(self.buttonLayout)
        self.verticalLayout_1.addLayout(self.horizontalLayout)
        self.stopBtn = QtWidgets.QPushButton()
        self.stopBtn.setObjectName("stopBtn")
        self.startBtn = QtWidgets.QPushButton()
        self.startBtn.setObjectName("startBtn")
        self.pauseBtn = QtWidgets.QPushButton()
        self.pauseBtn.setObjectName("pauseBtn")
        self.buttonLayout.addWidget(self.startBtn)
        self.buttonLayout.addWidget(self.pauseBtn)
        self.buttonLayout.addWidget(self.stopBtn)

        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.pid_tab = QtWidgets.QWidget()
        self.pid_tab.setObjectName("pid_tab")
        self.gridLayout = QtWidgets.QGridLayout(self.pid_tab)
        self.gridLayout.setObjectName("gridLayout")

        self.sp_label = QtWidgets.QLabel(self.pid_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sp_label.sizePolicy().hasHeightForWidth())
        self.sp_label.setSizePolicy(sizePolicy)
        self.sp_label.setObjectName("sp_label")
        self.gridLayout.addWidget(self.sp_label, 1, 1, 1, 1)

        self.ramp_rate_label = QtWidgets.QLabel(self.pid_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ramp_rate_label.sizePolicy().hasHeightForWidth())
        self.ramp_rate_label.setSizePolicy(sizePolicy)
        self.ramp_rate_label.setObjectName("ramp_rate")
        self.gridLayout.addWidget(self.ramp_rate_label, 3, 1, 1, 1)

        # button to set the setpoint and ramp rate
        self.setBtn = QtWidgets.QPushButton()
        self.setBtn.setObjectName("setBtn")
        #self.setBtn.setStyleSheet("background-color: yellow")
        self.gridLayout.addWidget(self.setBtn, 5, 1, 1, 4)

        # display current setpoint
        self.lcd2 = QLCDNumber()
        self.lcd2.setStyleSheet("QLCDNumber {color: white;}")
        self.lcd2.setSegmentStyle(QLCDNumber.Flat)
        self.lcd2.setDigitCount(6)
        self.gridLayout.addWidget(self.lcd2, 2, 4, 1, 2)

        # display current ramp rate
        self.lcd5 = QLCDNumber()
        self.lcd5.setStyleSheet("QLCDNumber {color: white;}")
        self.lcd5.setSegmentStyle(QLCDNumber.Flat)
        self.lcd5.setDigitCount(5)
        self.gridLayout.addWidget(self.lcd5, 4, 4, 1, 2)

        # display current temperature
        self.tempLabel = QtWidgets.QLabel(self.pid_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tempLabel.sizePolicy().hasHeightForWidth())
        self.tempLabel.setSizePolicy(sizePolicy)
        self.tempLabel.setObjectName("Display")
        self.gridLayout.addWidget(self.tempLabel, 6, 1, 1, 1)
        self.lcd = QLCDNumber()
        self.lcd.setStyleSheet("QLCDNumber {color: cyan;}")
        self.lcd.setSegmentStyle(QLCDNumber.Flat)
        self.lcd.setDigitCount(6)
        self.gridLayout.addWidget(self.lcd, 7, 1, 1, 4)

        self.sp_edit = QtWidgets.QLineEdit(self.pid_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sp_edit.sizePolicy().hasHeightForWidth())
        self.sp_edit.setSizePolicy(sizePolicy)
        self.sp_edit.setObjectName("sp_edit")
        self.sp_edit.setPlaceholderText('Enter a setpoint')
        self.sp_edit.setText('28') # default room temperature
        self.gridLayout.addWidget(self.sp_edit, 1, 4, 1, 1)
        self.plusBtn = QtWidgets.QPushButton()
        self.plusBtn.setObjectName("plusBtn")
        self.gridLayout.addWidget(self.plusBtn, 1, 5, 1, 1)
        self.minusBtn = QtWidgets.QPushButton()
        self.minusBtn.setObjectName("minusBtn")
        self.gridLayout.addWidget(self.minusBtn, 1, 6, 1, 1)

        self.ramp_rate_edit = QtWidgets.QLineEdit(self.pid_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ramp_rate_edit.sizePolicy().hasHeightForWidth())
        self.ramp_rate_edit.setSizePolicy(sizePolicy)
        self.ramp_rate_edit.setObjectName("ramp_rate_edit")
        self.ramp_rate_edit.setPlaceholderText('Enter a ramp rate')
        self.ramp_rate_edit.setText('1')  # default ramp rate
        self.gridLayout.addWidget(self.ramp_rate_edit, 3, 4, 1, 2)

        self.tabWidget.addTab(self.pid_tab, "")

        self.voltage_tab = QtWidgets.QWidget()
        self.voltage_tab.setObjectName("voltage_tab")
        self.vgridLayout = QtWidgets.QGridLayout(self.voltage_tab)
        self.vgridLayout.setObjectName("voltageGridLayout")

        # mode selection
        self.modeComboBox = QComboBox(self.voltage_tab)
        self.modeComboBox.addItem("Fixed voltage")
        self.modeComboBox.addItem("Ramp voltage")
        self.vgridLayout.addWidget(self.modeComboBox, 1, 1, 1, 1)

        self.v_label = QtWidgets.QLabel(self.voltage_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.v_label.sizePolicy().hasHeightForWidth())
        self.v_label.setSizePolicy(sizePolicy)
        self.v_label.setObjectName("v_label")
        self.vgridLayout.addWidget(self.v_label, 2, 1, 1, 1)

        self.ramp_time_label = QtWidgets.QLabel(self.voltage_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ramp_time_label.sizePolicy().hasHeightForWidth())
        self.ramp_time_label.setSizePolicy(sizePolicy)
        self.ramp_time_label.setObjectName("ramp_time")
        self.vgridLayout.addWidget(self.ramp_time_label, 3, 1, 1, 1)

        self.setvBtn = QtWidgets.QPushButton()
        self.setvBtn.setObjectName("setvBtn")
        self.vgridLayout.addWidget(self.setvBtn, 4, 1, 1, 4)

        # display current voltage
        self.vDisplayLabel = QtWidgets.QLabel(self.voltage_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vDisplayLabel.sizePolicy().hasHeightForWidth())
        self.vDisplayLabel.setSizePolicy(sizePolicy)
        self.vDisplayLabel.setObjectName("Voltage display")
        self.vgridLayout.addWidget(self.vDisplayLabel, 5, 1, 1, 1)
        self.lcd3 = QLCDNumber()
        self.lcd3.setStyleSheet("QLCDNumber {color: white;}")
        self.lcd3.setSegmentStyle(QLCDNumber.Flat)
        self.lcd3.setDigitCount(6)
        self.vgridLayout.addWidget(self.lcd3, 6, 1, 1, 4)

        # display current temperature
        self.tempLabel2 = QtWidgets.QLabel(self.voltage_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tempLabel2.sizePolicy().hasHeightForWidth())
        self.tempLabel2.setSizePolicy(sizePolicy)
        self.tempLabel2.setObjectName("Display")
        self.vgridLayout.addWidget(self.tempLabel2, 7, 1, 1, 1)
        self.lcd4 = QLCDNumber()
        self.lcd4.setStyleSheet("QLCDNumber {color: cyan;}")
        self.lcd4.setSegmentStyle(QLCDNumber.Flat)
        self.lcd4.setDigitCount(6)
        self.vgridLayout.addWidget(self.lcd4, 8, 1, 1, 4)

        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.vgridLayout.addLayout(self.horizontalLayout_3, 1, 2, 1, 1)
        self.v_edit = QtWidgets.QLineEdit(self.voltage_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.v_edit.sizePolicy().hasHeightForWidth())
        self.v_edit.setSizePolicy(sizePolicy)
        self.v_edit.setObjectName("v_edit")
        self.v_edit.setPlaceholderText('Enter a voltage')
        self.vgridLayout.addWidget(self.v_edit, 2, 4, 1, 2)

        self.ramp_time_edit = QtWidgets.QLineEdit(self.voltage_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ramp_time_edit.sizePolicy().hasHeightForWidth())
        self.ramp_time_edit.setSizePolicy(sizePolicy)
        self.ramp_time_edit.setObjectName("ramp_time_edit")
        self.ramp_time_edit.setPlaceholderText('Enter a ramp time')
        self.vgridLayout.addWidget(self.ramp_time_edit, 3, 4, 1, 2)

        self.tabWidget.addTab(self.voltage_tab, "")

        self.settings_tab = QtWidgets.QWidget()
        self.settings_tab.setObjectName("settings_tab")
        self.formLayout = QtWidgets.QFormLayout(self.settings_tab)
        self.formLayout.setObjectName("formLayout")
        self.label_p = QtWidgets.QLabel(self.settings_tab)
        self.label_p.setObjectName("label_p")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_p)
        self.edit_p = QtWidgets.QLineEdit(self.settings_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_p.sizePolicy().hasHeightForWidth())
        self.edit_p.setSizePolicy(sizePolicy)
        self.edit_p.setMaximumSize(QtCore.QSize(60, 16777215))
        self.edit_p.setObjectName("edit_p")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.edit_p)
        self.label_i = QtWidgets.QLabel(self.settings_tab)
        self.label_i.setObjectName("label_i")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_i)
        self.edit_i = QtWidgets.QLineEdit(self.settings_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_i.sizePolicy().hasHeightForWidth())
        self.edit_i.setSizePolicy(sizePolicy)
        self.edit_i.setMaximumSize(QtCore.QSize(60, 16777215))
        self.edit_i.setObjectName("edit_i")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.edit_i)
        self.label_d = QtWidgets.QLabel(self.settings_tab)
        self.label_d.setObjectName("label_d")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_d)
        self.edit_d = QtWidgets.QLineEdit(self.settings_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_d.sizePolicy().hasHeightForWidth())
        self.edit_d.setSizePolicy(sizePolicy)
        self.edit_d.setMaximumSize(QtCore.QSize(60, 16777215))
        self.edit_d.setObjectName("edit_d")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.edit_d)

        # read saved PID params
        saveFile = open("pid_ui.py", "r")
        PID_params = saveFile.readlines()[-1].split()  # [garbage, K_p, K_i, K_d]
        saveFile.close()
        self.edit_p.setText(PID_params[1])
        self.edit_i.setText(PID_params[2])
        self.edit_d.setText(PID_params[3])
        # save PID button
        self.saveBtn = QtWidgets.QPushButton(self.settings_tab)
        self.saveBtn.setObjectName("saveBtn")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.saveBtn)

        self.tabWidget.addTab(self.settings_tab, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tempPlot = PlotWidget(self.centralwidget)
        self.tempPlot.setMinimumSize(QtCore.QSize(600, 200))
        self.tempPlot.setObjectName("tempPlot")
        self.verticalLayout_2.addWidget(self.tempPlot)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 981, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle("TemperaturePID")
        self.stopBtn.setText("Stop/Clear PID loop")
        self.pauseBtn.setText("Pause the ramping")
        self.startBtn.setText("Start")
        self.sp_label.setText("Setpoint (C)")
        self.plusBtn.setText("+1")
        self.minusBtn.setText("-1")
        self.ramp_rate_label.setText("Ramp rate (C/min)")
        self.setBtn.setText("Update setpoint and ramp rate")
        self.setvBtn.setText("Update voltage and ramp time")
        self.tempLabel.setText("Temperature (C):")
        self.tempLabel2.setText("Temperature (C):")
        self.vDisplayLabel.setText("Voltage (V):")
        self.v_label.setText("Voltage (V)")
        self.ramp_time_label.setText("Ramp time (min)")

        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pid_tab), "PID")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.voltage_tab), "Voltage")
        self.label_p.setText("P")
        self.label_i.setText("I")
        self.label_d.setText("D")
        self.saveBtn.setText("Save PID values")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settings_tab), "PID values")

# store PID values:
# 3 0.032 0
# 2 0.033 0
# 1.5 0.010 0.0005
# 2 0.02 0.0
# 1 0.005 0.0
# 2 0.05 0.0
# 1.5 0.06 0.001
# 1.4 0.06 0.001